
name: CI-CD-Pipeline-to-AWS-Beanstalk
run-name: ${{ github.actor }} is learning GitHub Actions

env:
  EB_PACKAGE_S3_BACKET_NAME : "andr-flask-application-packages"
  EB_APPLICATION_NAME       : "My Page"
  EB_ENVIRONMENT_NAME       : "MyPage-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  
on:
  push:
    branches: 
      - master
   
jobs:
  my-ci-parts:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create zip deployment package      
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      
        
